openapi: 3.0.0
info:
  title: Swagger taskstore
  description: |
    This is a sample taskstore server.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://virtserver.swaggerhub.com/Rohitash/ToDoWebsite/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://taskstore.swagger.io/v2
tags:
- name: task
  description: Everything about your tasks
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
paths:
  /task:
    put:
      tags:
      - task
      summary: Update an existing task
      operationId: updatetask
      requestBody:
        $ref: '#/components/requestBodies/task'
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: task not found
        "405":
          description: Validation exception
      security:
      - taskstore_auth:
        - write:tasks
        - read:tasks
    post:
      tags:
      - task
      summary: Add a new task to the store
      operationId: addtask
      requestBody:
        $ref: '#/components/requestBodies/task'
      responses:
        "405":
          description: Invalid input
      security:
      - taskstore_auth:
        - write:tasks
        - read:tasks
  /task/findByStatus:
    get:
      tags:
      - task
      summary: Finds tasks by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findtasksByStatus
      parameters:
      - name: status
        in: query
        description: Status values that need to be considered for filter
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
            default: pending
            enum:
            - completed
            - pending
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/task'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/task'
        "400":
          description: Invalid status value
      security:
      - taskstore_auth:
        - write:tasks
        - read:tasks
  /task/{taskId}:
    get:
      tags:
      - task
      summary: Find task by ID
      description: Returns a single task
      operationId: gettaskById
      parameters:
      - name: taskId
        in: path
        description: ID of task to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
            application/xml:
              schema:
                $ref: '#/components/schemas/task'
        "400":
          description: Invalid ID supplied
        "404":
          description: task not found
      security:
      - api_key: []
    post:
      tags:
      - task
      summary: Updates a task in the store with form data
      operationId: updatetaskWithForm
      parameters:
      - name: taskId
        in: path
        description: ID of task that needs to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "405":
          description: Invalid input
      security:
      - taskstore_auth:
        - write:tasks
        - read:tasks
    delete:
      tags:
      - task
      summary: Deletes a task
      operationId: deletetask
      parameters:
      - name: api_key
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: taskId
        in: path
        description: task id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: task not found
      security:
      - taskstore_auth:
        - write:tasks
        - read:tasks
  /user:
    post:
      tags:
      - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
  /user/login:
    get:
      tags:
      - user
      summary: Logs user into the system
      operationId: loginUser
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              style: simple
              explode: false
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              style: simple
              explode: false
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
        "400":
          description: Invalid username/password supplied
  /user/logout:
    get:
      tags:
      - user
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        default:
          description: successful operation
  /user/{username}:
    get:
      tags:
      - user
      summary: Get user by user name
      operationId: getUserByName
      parameters:
      - name: username
        in: path
        description: The name that needs to be fetched. Use user1 for testing.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Invalid username supplied
        "404":
          description: User not found
    put:
      tags:
      - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
      - name: username
        in: path
        description: name that need to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Updated user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "400":
          description: Invalid user supplied
        "404":
          description: User not found
    delete:
      tags:
      - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
      - name: username
        in: path
        description: The name that needs to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid username supplied
        "404":
          description: User not found
components:
  schemas:
    User:
      required:
      - email
      - password
      - username
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        tasks:
          type: array
          description: List of task object
          items:
            $ref: '#/components/schemas/task'
      xml:
        name: User
    task:
      required:
      - name
      - start_date
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        status:
          type: string
          description: task status in the store
          enum:
          - completed
          - pending
      xml:
        name: task
    body:
      type: object
      properties:
        name:
          type: string
          description: Updated name of the task
        status:
          type: string
          description: Updated status of the task
  requestBodies:
    task:
      description: task object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/task'
        application/xml:
          schema:
            $ref: '#/components/schemas/task'
      required: true
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      required: true
  securitySchemes:
    taskstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://taskstore.swagger.io/oauth/dialog
          scopes:
            write:tasks: modify tasks in your account
            read:tasks: read your tasks
    api_key:
      type: apiKey
      name: api_key
      in: header
